/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppRewardsRouteImport } from './routes/_app/rewards'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppPredictionsRouteImport } from './routes/_app/predictions'
import { Route as AppLeaderboardRouteImport } from './routes/_app/leaderboard'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppRewardsRoute = AppRewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPredictionsRoute = AppPredictionsRouteImport.update({
  id: '/predictions',
  path: '/predictions',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaderboardRoute = AppLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/leaderboard': typeof AppLeaderboardRoute
  '/predictions': typeof AppPredictionsRoute
  '/profile': typeof AppProfileRoute
  '/rewards': typeof AppRewardsRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/leaderboard': typeof AppLeaderboardRoute
  '/predictions': typeof AppPredictionsRoute
  '/profile': typeof AppProfileRoute
  '/rewards': typeof AppRewardsRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/leaderboard': typeof AppLeaderboardRoute
  '/_app/predictions': typeof AppPredictionsRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/rewards': typeof AppRewardsRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/leaderboard'
    | '/predictions'
    | '/profile'
    | '/rewards'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/leaderboard' | '/predictions' | '/profile' | '/rewards' | '/'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/leaderboard'
    | '/_app/predictions'
    | '/_app/profile'
    | '/_app/rewards'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rewards': {
      id: '/_app/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof AppRewardsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/predictions': {
      id: '/_app/predictions'
      path: '/predictions'
      fullPath: '/predictions'
      preLoaderRoute: typeof AppPredictionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leaderboard': {
      id: '/_app/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AppLeaderboardRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppLeaderboardRoute: typeof AppLeaderboardRoute
  AppPredictionsRoute: typeof AppPredictionsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppRewardsRoute: typeof AppRewardsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppLeaderboardRoute: AppLeaderboardRoute,
  AppPredictionsRoute: AppPredictionsRoute,
  AppProfileRoute: AppProfileRoute,
  AppRewardsRoute: AppRewardsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
