/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppRewardsRouteImport } from './routes/_app/rewards'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppPredictionsRouteImport } from './routes/_app/predictions'
import { Route as AppLeaderboardRouteImport } from './routes/_app/leaderboard'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as ApiPublicSyncExternalScoresRouteImport } from './routes/api/public/sync-external-scores'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppRewardsRoute = AppRewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPredictionsRoute = AppPredictionsRouteImport.update({
  id: '/predictions',
  path: '/predictions',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaderboardRoute = AppLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicSyncExternalScoresRoute =
  ApiPublicSyncExternalScoresRouteImport.update({
    id: '/api/public/sync-external-scores',
    path: '/api/public/sync-external-scores',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AppAdminRoute
  '/leaderboard': typeof AppLeaderboardRoute
  '/predictions': typeof AppPredictionsRoute
  '/profile': typeof AppProfileRoute
  '/rewards': typeof AppRewardsRoute
  '/api/public/sync-external-scores': typeof ApiPublicSyncExternalScoresRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AppAdminRoute
  '/leaderboard': typeof AppLeaderboardRoute
  '/predictions': typeof AppPredictionsRoute
  '/profile': typeof AppProfileRoute
  '/rewards': typeof AppRewardsRoute
  '/': typeof AppIndexRoute
  '/api/public/sync-external-scores': typeof ApiPublicSyncExternalScoresRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/leaderboard': typeof AppLeaderboardRoute
  '/_app/predictions': typeof AppPredictionsRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/rewards': typeof AppRewardsRoute
  '/_app/': typeof AppIndexRoute
  '/api/public/sync-external-scores': typeof ApiPublicSyncExternalScoresRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/sitemap.xml'
    | '/admin'
    | '/leaderboard'
    | '/predictions'
    | '/profile'
    | '/rewards'
    | '/api/public/sync-external-scores'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/sitemap.xml'
    | '/admin'
    | '/leaderboard'
    | '/predictions'
    | '/profile'
    | '/rewards'
    | '/'
    | '/api/public/sync-external-scores'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/sitemap.xml'
    | '/_app/admin'
    | '/_app/leaderboard'
    | '/_app/predictions'
    | '/_app/profile'
    | '/_app/rewards'
    | '/_app/'
    | '/api/public/sync-external-scores'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicSyncExternalScoresRoute: typeof ApiPublicSyncExternalScoresRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rewards': {
      id: '/_app/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof AppRewardsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/predictions': {
      id: '/_app/predictions'
      path: '/predictions'
      fullPath: '/predictions'
      preLoaderRoute: typeof AppPredictionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leaderboard': {
      id: '/_app/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AppLeaderboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/sync-external-scores': {
      id: '/api/public/sync-external-scores'
      path: '/api/public/sync-external-scores'
      fullPath: '/api/public/sync-external-scores'
      preLoaderRoute: typeof ApiPublicSyncExternalScoresRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppLeaderboardRoute: typeof AppLeaderboardRoute
  AppPredictionsRoute: typeof AppPredictionsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppRewardsRoute: typeof AppRewardsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppLeaderboardRoute: AppLeaderboardRoute,
  AppPredictionsRoute: AppPredictionsRoute,
  AppProfileRoute: AppProfileRoute,
  AppRewardsRoute: AppRewardsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicSyncExternalScoresRoute: ApiPublicSyncExternalScoresRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
